# Generated by Django 6.0.5 on 2026-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
